version: '3'

services:

  app:
    build: 
      context: ./
      args:
        NODE_ENV: development
    command: yarn run dev:sever
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./:/app:delegated
    ports:
      - '3000:3000'

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: api
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: api